chore: add shell and docker fmt pre commit hooks
Signed-off-by: Akshay Patidar <akshaypatidar1999@gmail.com>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -13,6 +13,7 @@ on:
 jobs:
   ci:
     runs-on: ubuntu-latest
+    environment: ci
     steps:
       - name: Checkout code
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
@@ -31,6 +32,15 @@ jobs:
           distribution: 'temurin'
           cache: 'maven'
           overwrite-settings: false
+
+      - name: Check version from pom.xml
+        run: |
+          PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+          echo "PROJECT_VERSION: ${PROJECT_VERSION}"
+          if [[ ${PROJECT_VERSION} != *-SNAPSHOT ]]; then
+            echo "::error::Error: version must be suffixed with '-SNAPSHOT'. Concrete versions can only be released from master branch"
+            exit 1
+          fi
 
       - name: Set up QEMU
         uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
